# Compiler.  One of the following:
#
#     gcc: The GNU compiler suit
#
URT_CONFIG_CC=gcc

# Platform.  One of the following:
#
#     linux:            Non-real-time library for Linux  (Not yet implemented)
#     rtai:             Real-time library and kernel module for Linux  (Not yet implemented)
#     rtai-kernel-only: Real-time kernel module for Linux  (Not yet implemented)
#     rtai-user-only:   Real-time library for Linux  (Not yet implemented)
#     qnx:              Real-time library for QNX  (Not yet implemented)
#     vxworks:          Real-time library for VxWorks  (Not yet implemented)
#
# In the future, other systems may also be considered, such as mac or even windows.
URT_CONFIG_RT_SUBSYSTEM=linux

# Platform dependent configurations:
#
# Linux: None
# RTAI:
#     rtai tool: path to rtai-config script
URT_CONFIG_RTAI_TOOL=/usr/realtime/bin/rtai-config
# QNX: None
# VxWorks: None

# Whether it should build in Debug mode
URT_CONFIG_DEBUG=y

# Whether it should use color in build
URT_CONFIG_COLOR_BUILD=y
