# Compiler.  One of the following:
#
#     gcc: The GNU compiler suit
#
URT_CONFIG_CC=gcc

# Platform.  One of the following:
#
#     linux:            Non-real-time library for Linux  (Not yet implemented)
#     rtai:             Real-time library and kernel module for Linux  (Not yet implemented)
#     rtai-kernel-only: Real-time kernel module for Linux  (Not yet implemented)
#     rtai-user-only:   Real-time library for Linux  (Not yet implemented)
#     qnx:              Real-time library for QNX  (Not yet implemented)
#     vxworks:          Real-time library for VxWorks  (Not yet implemented)
#
# In the future, other systems may also be considered, such as mac or even windows.
URT_CONFIG_RT_SUBSYSTEM=linux

# Platform dependent configurations:
#
# Linux: None
# RTAI:
#     rtai tool: path to rtai-config script
URT_CONFIG_RTAI_TOOL=/usr/realtime/bin/rtai-config
# QNX: None
# VxWorks: None

# Parameters
#
#     max shared objects: Maximum possible number of shared objects (memory, locks etc)
#     lock stop max delay: Lock operations have a parameter that enables them to stop and return even if lock is not acquired.
#                          For example, to recover from a dead-lock or on application exit.  This parameter defines what is the
#                          maximum delay possible until the function responds to the cancellation.  Higher values decrease
#                          responsiveness in such cases, while decreasing processor usage.  Too low values would result in busy waiting.
URT_CONFIG_MAX_SHARED_OBJECTS=4096
URT_CONFIG_LOCK_STOP_MAX_DEALY=10000000
URT_CONFIG_DEFAULT_STACK_SIZE=4096

# Whether it should build in Debug mode
URT_CONFIG_DEBUG=y

# Whether it should use color in build
URT_CONFIG_COLOR_BUILD=y

# Whether this is a developer build
URT_CONFIG_DEVELOPER_MODE=y

# Whether documentation must be build
URT_CONFIG_BUILD_DOC=n
