# this file is included by */Makefile

include ../../Makefile.config
include ../../Makefile.common

URT_BASE := $(abspath $(CURDIR)/../..)
include $(URT_BASE)/build/Makefile.build
CFLAGS := $(URT_USER_CFLAGS) $(EXTRA_CFLAGS)
# USE_SHARED defined in including Makefile decides whether to build against static or shared lib
ifeq ($(USE_SHARED), y)
  LDFLAGS := -L$(URT_BASE)/build/shared -lurt-$(URT_VERSION) $(URT_USER_LDFLAGS) $(LDFLAGS) $(EXTRA_LDFLAGS)
else
  LDFLAGS := -L$(URT_BASE)/build/static -lurt $(URT_USER_LDFLAGS) $(LDFLAGS) $(EXTRA_LDFLAGS)
endif
# TARGET and possibly TARGET2 defined by including Makefile

.PHONY: all dep clean
all: dep $(TARGET) $(TARGET2)
	@$(SHELL_NOOP)
clean:
	-$(RM) $(TARGET) $(TARGET2) *.o Makefile.dep
dep: Makefile.dep
	@$(SHELL_NOOP)
LIB_HDR :=
include $(URT_BASE)/include/Makefile.src
include $(URT_SYS)/include/Makefile.src
VPATH := $(URT_BASE)/include:$(URT_SYS)/include
# source dependencies of Makefile.dep defined in including Makefile
Makefile.dep: $(LIB_HDR)
	$(CC) $(CFLAGS) $(CC_M) $(filter-out %.h,$^) > Makefile.dep

# further dependencies of TARGET and possibly TARGET2 defined by including Makefile
$(TARGET): $(URT_BASE)/build/shared/liburt-$(URT_VERSION).so
	$(LD) $(LD_o) $@ $(filter-out %.so,$^) $(LDFLAGS)
ifdef TARGET2
$(TARGET2): $(URT_BASE)/build/shared/liburt-$(URT_VERSION).so
	$(LD) $(LD_o) $@ $(filter-out %.so,$^) $(LDFLAGS)
endif
%.o: %.c
	$(CC) $(CFLAGS) $(CC_o) $@ $<

.PHONY: execute_test valgrind_check
execute_test:
	@./$(TARGET) 2>&1 | grep --color=never 'internal error'
valgrind_check:
	@valgrind --leak-check=full ./$(TARGET) 2>&1 | grep --color=never 'in use at exit:\|== Invalid\|internal error'

-include Makefile.dep
