#! /bin/bash

urt_version="@URT_VERSION@"
urt_prefix="@URT_PREFIX@"
urt_sys="@URT_SYS@"
urt_include_dir="$urt_prefix/include"
urt_lib_dir="$urt_prefix/lib"
urt_modules_dir="$urt_prefix/modules"
urt_bin_dir="$urt_prefix/bin"
urt_cc="@URT_CC@"
urt_ld="@URT_LD@"
urt_kernel_cflags="@URT_KERNEL_CFLAGS@ -I'$urt_include_dir' -I'$urt_include_dir/sys'"
urt_kernel_symbols="@URT_KERNEL_SYMBOLS@ '$urt_modules_dir'/Module.symvers"
urt_user_cflags="@URT_USER_CFLAGS@ -I'$urt_include_dir' -I'$urt_include_dir/sys'"
urt_user_static_ldflags="-L'$urt_lib_dir' -l'urt@URT_SUFFIX@' @URT_USER_LDFLAGS@"
urt_user_shared_ldflags="-L'$urt_lib_dir' -l'urt@URT_SUFFIX@-$urt_version' @URT_USER_LDFLAGS@"

urt_has_kernel="@URT_HAS_KERNEL@"
urt_has_user="@URT_HAS_USER@"

msg_help_has_kernel=
msg_help_has_user=
[ "$urt_has_kernel" != y ] && msg_help_has_kernel=" (not available)"
[ "$urt_has_user" != y ] && msg_help_has_user=" (not available)"

usage() {
cat <<EOF
Usage urt-config OPTIONS
Options :
    --help                  print this help message
    --version               print URT version
    --sys                   Subsystem being used by URT
    --cc                    C compiler URT was built with
    --ld                    linker capable of linking against URT
    --prefix                installation path of URT
    --bin-dir               path to URT executables
    --include-dir           path to URT headers
    --lib-dir               path to URT library files$msg_help_has_user
    --module-dir            path to URT kernel module files$msg_help_has_kernel
    --user-cflags           C flags for user-space applications$msg_help_has_user
    --user-ldflags-static   link flags for user-space applications
                               (against static library)$msg_help_has_user
    --user-ldflags-shared   link flags for user-space applications
                               (against shared library)$msg_help_has_user
    --kernel-cflags         C flags for kernel modules$msg_help_has_kernel
    --kernel-symbols        symbol information for kernel modules
                               (for KBUILD_EXTRA_SYMBOLS)$msg_help_has_kernel
    --build-user            whether build for user-space applications is possible (y/n)
    --build-kernel          whether build for kernel-modules is possible (y/n)
    --tool-clear            tool to clear objects from registry
    --tool-names            tool to list objects in the registry
    --tool-recover          tool to recover registry from crash
    --tool-dump             tool to dump contents of memory

    --no-new-line           instruct this script to not output new-line
EOF
    exit $1
}

output_new_line=true

unavailable() {
    echo "URT was not built to support $1"
    usage 1 1>&2
}

output() {
    if $output_new_line; then
        echo "$1";
    else
        printf -- "$1";
    fi
}

if test $# -eq 0; then
    usage 1 1>&2
fi

shopt -s extglob

while [ $# -gt 0 ]; do
    case "$1" in
        --help)
            usage 0
            ;;
        --version)
            output "$urt_version"
            ;;
        --sys)
            output "$urt_sys"
            ;;
        --cc)
            output "$urt_cc"
            ;;
        --ld)
            output "$urt_ld"
            ;;
        --prefix)
            output "$urt_prefix"
            ;;
        --bin-dir)
            output "$urt_bin_dir"
            ;;
        --include-dir)
            output "$urt_include_dir"
            ;;
        --lib-dir)
            [ "$urt_has_user" == y ] && output "$urt_lib_dir" || unavailable "user-space applications"
            ;;
        --module-dir)
            [ "$urt_has_kernel" == y ] && output "$urt_modules_dir" || unavailable "kernel modules"
            ;;
        --u*-cflags)
            [ "$urt_has_user" == y ] && output "$urt_user_cflags" || unavailable "user-space applications"
            ;;
        --u*-ldflags-static)
            [ "$urt_has_user" == y ] && output "$urt_user_static_ldflags" || unavailable "user-space applications"
            ;;
        --u*-ldflags?(-shared))
            [ "$urt_has_user" == y ] && output "$urt_user_shared_ldflags" || unavailable "user-space applications"
            ;;
        --k*-cflags|--m*-cflags)
            [ "$urt_has_kernel" == y ] && output "$urt_kernel_cflags" || unavailable "kernel modules"
            ;;
        --k*-sym*|--m*-sym*)
            [ "$urt_has_kernel" == y ] && output "$urt_kernel_symbols" || unavailable "kernel modules"
            ;;
        --build-u*|--has-u*)
            output "$urt_has_user"
            ;;
        --build-k*|--has-k*)
            output "$urt_has_kernel"
            ;;
        --tool-clear)
            output "$urt_bin_dir"/urt_clear
            ;;
        --tool-names)
            output "$urt_bin_dir"/urt_names
            ;;
        --tool-recover)
            output "$urt_bin_dir"/urt_recover
            ;;
        --tool-dump)
            output "$urt_bin_dir"/urt_dump
            ;;
        --no-new*line)
            output_new_line=false
            ;;
        *)
            usage 1 1>&2
            ;;
    esac
    shift
done
