#! /bin/sh

urt_version="@URT_VERSION@"
urt_prefix="@URT_PREFIX@"
urt_include_dir="$URT_PREFIX/include"
urt_lib_dir="$URT_PREFIX/lib"
urt_modules_dir="$URT_PREFIX/modules"
urt_bin_dir="$URT_PREFIX/bin"
urt_cc="@URT_CC@"
urt_ld="@URT_LD@"
urt_kernel_cflags="@URT_KERNEL_CFLAGS@ -I\"$URT_INCLUDE_DIR\" -I\"$URT_INCLUDE_DIR/sys\""
urt_kernel_symbols="@URT_KERNEL_SYMBOLS@ \"$URT_MODULES_DIR\"/Module.symvers"
urt_user_cflags="@URT_USER_CFLAGS@ -I\"$URT_INCLUDE_DIR\" -I\"$URT_INCLUDE_DIR/sys\""
urt_user_static_ldflags="-L\"$URT_LIB_DIR\" -l\"urt@URT_SUFFIX@\" @URT_USER_LDFLAGS@"
urt_user_shared_ldflags="-L\"$URT_LIB_DIR\" -l\"urt@URT_SUFFIX@-$URT_VERSION\" @URT_USER_LDFLAGS@"

urt_has_kernel="@URT_HAS_KERNEL@"
urt_has_user="@URT_HAS_USER@"

msg_help_has_kernel=
msg_help_has_user=
[ "$urt_has_kernel" != y ] && msg_help_has_kernel=" (not available)"
[ "$urt_has_user" != y ] && msg_help_has_user=" (not available)"

usage() {
cat <<EOF
Usage urt-config OPTIONS
Options :
    --help                  print this help message
    --version               print URT version
    --cc                    C compiler URT was built with
    --ld                    linker capable of linking against URT
    --prefix                installation path of URT
    --bin-dir               path to URT executables
    --include-dir           path to URT headers
    --lib-dir               path to URT library files$msg_help_has_user
    --module-dir            path to URT kernel module files$msg_help_has_kernel
    --user-cflags           C flags for user-space applications$msg_help_has_user
    --user-ldflags-static   link flags for user-space applications
                               (against static library)$msg_help_has_user
    --user-ldflags-shared   link flags for user-space applications
                               (against shared library)$msg_help_has_user
    --kernel-cflags         C flags for kernel modules$msg_help_has_kernel
    --kernel-symbols        symbol information for kernel modules
                               (for KBUILD_EXTRA_SYMBOLS)$msg_help_has_kernel
EOF
    exit $1
}

unavailable() {
    echo "URT was not built to support $1"
    usage 1 1>&2
}

if test $# -eq 0; then
    usage 1 1>&2
fi

while [ $# -gt 0 ]; do
    case "$1" in
        --help)
            usage 0
            ;;
        --version)
            echo $urt_version
            ;;
        --cc)
            echo $urt_cc
            ;;
        --ld)
            echo $urt_ld
            ;;
        --prefix)
            echo $urt_prefix
            ;;
        --bin-dir)
            echo $urt_bin_dir
            ;;
        --include-dir)
            echo $urt_include_dir
            ;;
        --lib-dir)
            [ "$urt_has_user" == y ] && echo $urt_lib_dir || unavailable "user-space applications"
            ;;
        --module-dir)
            [ "$urt_has_kernel" == y ] && echo $urt_modules_dir || unavailable "kernel modules"
            ;;
        --u*-cflags)
            [ "$urt_has_user" == y ] && echo $urt_user_cflags || unavailable "user-space applications"
            ;;
        --u*-ldflags-static)
            [ "$urt_has_user" == y ] && echo $urt_user_static_ldflags || unavailable "user-space applications"
            ;;
        --u*-ldflags?(-shared))
            [ "$urt_has_user" == y ] && echo $urt_user_shared_ldflags || unavailable "user-space applications"
            ;;
        --k*-cflags|--m*-cflags)
            [ "$urt_has_kernel" == y ] && echo $urt_kernel_cflags || unavailable "kernel modules"
            ;;
        --k*-sym*|--m*-sym*)
            [ "$urt_has_kernel" == y ] && echo $urt_kernel_symbols || unavailable "kernel modules"
            ;;
        *)
            usage 1 1>&2
            ;;
    esac
    shift
done
