#ifndef URT_INTERNAL_CONFIG_H
#define URT_INTERNAL_CONFIG_H

#define URT_MAX_OBJECTS			@URT_MAX_OBJECTS@
#define URT_LOCK_STOP_MAX_DELAY		@URT_LOCK_STOP_MAX_DELAY@
#define URT_DEFAULT_STACK_SIZE		@URT_DEFAULT_STACK_SIZE@

#endif
