#ifndef URT_VERSION_H
#define URT_VERSION_H

#define URT_STRINGIFY_(x)	#x
#define URT_STRINGIFY(x)	URT_STRINGIFY_(x)
#define URT_VERSION_MAJOR	@URT_VERSION_MAJOR@
#define URT_VERSION_MINOR	@URT_VERSION_MINOR@
#define URT_VERSION_REVISION	@URT_VERSION_REVISION@
#define URT_VERSION_BUILD	@URT_VERSION_BUILD@
#define URT_VERSION		URT_STRINGIFY(URT_VERSION_MAJOR)"."\
				URT_STRINGIFY(URT_VERSION_MINOR)"."\
				URT_STRINGIFY(URT_VERSION_REVISION)"."\
				URT_STRINGIFY(URT_VERSION_BUILD)

#endif
